### ISSUE TITLE
Single line comments can start with //

### ISSUE THREAD

**Issue by joshuajabbour** [GiantToast/language-terraform#12]
This is valid syntax per the spec: https://github.com/hashicorp/hcl

**Comment by GiantToast** [comment]
Fixed and pushed an update.

**Comment by joshuajabbour** [comment]
So fast, thanks!

**Comment by sheeley** [comment]
@GiantToast I often comment out single lines within blocks I later toggle, which causes problems:
```
resource "aws_autoscaling_group" "nomad" {
  ...
  /*load_balancers = ["${aws_elb.api.name}"]*/
  ...
}
```
```
/*
resource "aws_autoscaling_group" "nomad" {
  ...
  /*load_balancers = ["${aws_elb.api.name}"]*/ <-- this breaks
  ...
}
*/
```

Would you be into a PR that comments a single line using `#` or `//` rather than `/* */`?
