### ISSUE TITLE
using $file causes syntax highlighting issues

### ISSUE THREAD

**Issue by zapman449** [GiantToast/language-terraform#13]
The third line in this stanza does not get highlighted correctly:

resource "aws_key_pair" "deployer" {
  key_name = "deployer-key"
  public_key = "$file("ssh_keys/production_${var.aws_region}.pem.pub")"
}

It seems to not process the quotes properly when nested inside other parens or curly braces.

**Comment by tranberg** [comment]
According to the [documentation](https://www.terraform.io/docs/configuration/interpolation.html) you should use curly braces:
>Built-in Functions
Terraform ships with built-in functions. Functions are called with the syntax name(arg, arg2, ...). For example, to read a file: ${file("path.txt")}. The built-in functions are documented below.

This will get highlighted properly:

resource "aws_key_pair" "deployer" {
key_name = "deployer-key"
public_key = "${file("ssh_keys/production_${var.aws_region}.pem.pub")}"
}

**Comment by zapman449** [comment]
Thank you
