### ISSUE TITLE
Syntax coloring breaks on second set of curly-braces

### ISSUE THREAD

**Issue by GeertJohan** [GiantToast/language-terraform#16]
Given this line:
```terraform
template = "${file("${path.module}/my-file-name")}"
```

The syntax coloring breaks. If I remove `${path.module}` it works fine.

**Comment by tranberg** [comment]
Is this still an issue? I can't reproduce it.

**Comment by GiantToast** [comment]
I also tried it out and can no longer reproduce.  Closing issue.
