### ISSUE TITLE
doesn't handle 'heredoc' style strings

### ISSUE THREAD

**Issue by MattFenner** [GiantToast/language-terraform#19]
doesn't handle termination of heredoc comments correctly

![image](https://cloud.githubusercontent.com/assets/1695492/15413438/8b850322-1e73-11e6-874c-5e88a12ca023.png)

**Comment by GiantToast** [comment]
According to the documentation, the terminating marker cannot be indented.
https://www.terraform.io/docs/configuration/syntax.html

**Comment by GiantToast** [comment]
Going to go ahead and close this.

**Comment by MattFenner** [comment]
it was working ok. wouldnt it just put an extra line with an indent into your string?
