### ISSUE TITLE
Keywords, Variables, Strings, not Highlighted

### ISSUE THREAD

**Issue by darkn3rd** [GiantToast/language-terraform#22]
Keywords are not highlight.  
Strings not highlighted.  
Variables in strings not highlighted.

Some hints from: https://github.com/alexlouden/Terraform.tmLanguage

**Comment by GiantToast** [comment]
I'm going to go ahead and close this since no one else seems to have issues with the current highlighting.

I would happily test out and merge in a pull request to fix this if someone wants to take it on.
