### ISSUE TITLE
Error for comment in block 

### ISSUE THREAD

**Issue by tony612** [GiantToast/language-terraform#4]
![default_tf_-__users_tony_repo_projects_lls_terraform-generator_-_atom](https://cloud.githubusercontent.com/assets/1253659/8694092/f841c44a-2b0e-11e5-864b-bdc389296833.png)

The comment in block highlight is wrong

**Comment by GiantToast** [comment]
Thanks, I'll take a look at this tomorrow and will try to get a fix in.

**Comment by GiantToast** [comment]
This should be fixed in the version just released.  Let me know if it works for you and I'll close this.
