### ISSUE TITLE
Interpolated vars not always parsed correctly

### ISSUE THREAD

**Issue by josh-padnick** [GiantToast/language-terraform#5]
First, great plugin!  This makes working with Terraform in Atom a pleasure.

The issue I've run into is that we use a lot of variable interpolations in our code, and the parser doesn't seem to be picking them up correctly.  Observe:

![image](https://cloud.githubusercontent.com/assets/4295964/8706324/14b16b88-2ae4-11e5-8edc-a703578a874e.png)

In this case, the following lines are not parsed correctly:

- `cidr_block = "${format("%s.0.0/18", "${var.cidr_block_first_two}")}"` -- interpolation not formatted correctly.
- `tags { Name = "${format("%s-vpc", "${var.vpc_name}")}" }` -- interpolation not formatted correctly.
- `#tags { Name = "prod-vpc" }` -- should be commented out.

**Comment by GiantToast** [comment]
Sorry it's taken me so long to respond to this, I've been swamped at work.  I should be able to get a fix in for this sometime tomorrow.  Thanks for the feedback!

**Comment by josh-padnick** [comment]
No problem. Thanks for this great plugin!  We use it all the time.

**Comment by GiantToast** [comment]
Does this look like you would expect:

![sample_fix](https://cloud.githubusercontent.com/assets/965556/9186805/ead5590e-3f8e-11e5-881a-cc5f53483c4b.png)

If so, I can go ahead and merge my changes and cut a new release.

**Comment by josh-padnick** [comment]
Looks great!  I think the key is to allow for arbitrarily nested interpolations in purple while keeping the surrounding `"${...}"` in green, as you've done.

I suppose it'd be possible to format individual interpolations so that, for example, `format` was in a separate color, but this is great, and still a big step up.

Thx for updating this!

**Comment by GiantToast** [comment]
New version has been tagged and released. I'm going to go ahead and close this, feel free to open it back up if something isn't right.

**Comment by josh-padnick** [comment]
I believe I found a case where there's a bug.  Observe:

![image](https://cloud.githubusercontent.com/assets/4295964/10801407/85b548c6-7d74-11e5-95c8-d1250c4506f8.png)

`assume_role_policy` doesn't parse correctly, and unfortunately this breaks parsing for the rest of the file.
