### ISSUE TITLE
Nested Interpolations break the syntax highlighting

### ISSUE THREAD

**Issue by j0nesin** [GiantToast/language-terraform#9]
Terraform 0.6.7 release changes the way template files are referenced to typically follow this pattern with nested interpolations.

template = "${file("${path.module}/filename.tpl")}"

The syntax highlighting loses sync as it associates the internal closing bracket with the external opening bracked causing the remainder of the file to by highlighted incorrectly.

Thanks for the plugin.

**Comment by crumley** [comment]
:+1:

**Comment by josh-padnick** [comment]
Ran into this exact issue.  

Formats correctly but fails to run with Terraform:
![screenshot 2016-01-12 11 24 55](https://cloud.githubusercontent.com/assets/4295964/12272749/1f5fb03e-b91f-11e5-8f78-fe0ebfa057b3.png)

Formats incorrectly but runs successfully with Terraform:
![screenshot 2016-01-12 11 24 16](https://cloud.githubusercontent.com/assets/4295964/12272736/0b3fc760-b91f-11e5-83b3-88a5fef76559.png)

Notice how an inner set of quotes is required, but then the plugin stops formatting comments correctly.

**Comment by stvnwrgs** [comment]
+1

**Comment by GiantToast** [comment]
Should be fixed in the new release. Thanks @johnrengelman for the pull request.
